name: scan_device_qr_code
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # connectivity_plus: ^6.0.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  http: ^1.2.1
  internet_connection_checker_plus: ^2.5.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "icons/app_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.png
    - assets/images/homeScr.png
