// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsClw3LKQsqg04kfL2AuSy9cUnwcav38',
    appId: '1:438714719320:web:70ae22cc6c32cd5a3f7e2d',
    messagingSenderId: '438714719320',
    projectId: 'devicevalidator-dc1e3',
    authDomain: 'devicevalidator-dc1e3.firebaseapp.com',
    storageBucket: 'devicevalidator-dc1e3.appspot.com',
    measurementId: 'G-0NTDSY96CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHV1ud7of01ifjFayJrDFld57bAGAMPvE',
    appId: '1:438714719320:android:542baeae92cf262c3f7e2d',
    messagingSenderId: '438714719320',
    projectId: 'devicevalidator-dc1e3',
    storageBucket: 'devicevalidator-dc1e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZTHqpjgZ5XdQjgzxHuJ0L4s73hs-UKY',
    appId: '1:438714719320:ios:b3b628cd4f99db463f7e2d',
    messagingSenderId: '438714719320',
    projectId: 'devicevalidator-dc1e3',
    storageBucket: 'devicevalidator-dc1e3.appspot.com',
    iosBundleId: 'com.example.scanDeviceQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuZTHqpjgZ5XdQjgzxHuJ0L4s73hs-UKY',
    appId: '1:438714719320:ios:b3b628cd4f99db463f7e2d',
    messagingSenderId: '438714719320',
    projectId: 'devicevalidator-dc1e3',
    storageBucket: 'devicevalidator-dc1e3.appspot.com',
    iosBundleId: 'com.example.scanDeviceQrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVsClw3LKQsqg04kfL2AuSy9cUnwcav38',
    appId: '1:438714719320:web:5c46ab1a86c0039e3f7e2d',
    messagingSenderId: '438714719320',
    projectId: 'devicevalidator-dc1e3',
    authDomain: 'devicevalidator-dc1e3.firebaseapp.com',
    storageBucket: 'devicevalidator-dc1e3.appspot.com',
    measurementId: 'G-XFB9WB9V2D',
  );
}
